# Jekyll configuration

theme: jekyll-theme-leap-day

title: The Yelda Documents
description: Be the best Diabetic retinopathy diagnostic system

encoding: "utf-8"

highlighter: rouge
markdown: kramdown

exclude: ["drafts", "Gemfile*", "README.md", "LICENSE", "*.bak", ".gitignore"]

